README.md

Hi Ismail! I was using this carousel and it's awesome but I realised that readme maybe was wrong `:items-to-show` should go in `<carousel>` instead of `<slide>`

docs: fix readme items-to-show to carousel component

---

src/components/Navigation.ts
src/components/Pagination.ts

In the current implementation of this library, a lighthouse error is triggered for accessibility concerns for the pagination buttons. I added aria labels that are descriptive to both the navigation arrows as well as the pagination buttons.

Added aria-label to navigation and pagination buttons

---

src/components/Carousel.ts

Fixes #121.
When first entering the `handleDragStart` function, the `isTouch` variable was initially `false`. Its assignment was moved to the top of the function.

fix: Carousel needed double clicks for clicks to work

---

src/partials/utils.ts

This check fixes bug https://github.com/ismail9k/vue3-carousel/issues/133#issue-1072291456
This adds an additional check for the case when `currentSlide` passed to the getSlidesToScroll function as a fraction number. It happens when the last item in the non-wrapped carousel is rendered partial.
```
<template>
<Carousel :items-to-show="2.5" :settings="settings" id="hideArrowsExample">
<Slide v-for="slide in 5" :key="slide">
<div class="carousel__item">{{ slide }}</div>
</Slide>
<template #addons>
<Navigation />
</template>
</Carousel>
</template>
<script>
import { defineComponent } from 'vue';
import { Carousel, Slide, Navigation } from '../../dist/carousel.es';
import '../../dist/carousel.css';
export default defineComponent({
name: 'HiddenArrows',
components: {
Carousel,
Slide, …
```

Fix #issue-1072291456

---

src/components/Carousel.ts

It fixes #193 issue. Before on touch devices it was necessary  double click to fire event.

fix: Fixed click event inside slide on touch devices

---

docs/examples/ExampleCustomNavigation.vue
src/components/Carousel.ts

Stop watching `modelValue` to prevent carousel double update
closes #212

Bug fix/#212/v model

---

src/utils/getSlidesVNodes.ts

fix #248
Enabled to use v-if in Slide
But if you want to switch dynamically, you need to re-render the Carousel with `:key` etc.

bugfix #248

---

src/components/Carousel.ts

fix https://github.com/ismail9k/vue3-carousel/issues/226 https://github.com/ismail9k/vue3-carousel/issues/220
input tag is clickable
Instead the input tag will not be draggable

fix: allow clicks on input

---

src/components/Carousel.ts
src/partials/defaults.ts
src/partials/props.ts
src/types/carousel.ts
src/utils/throttle.ts

By default, this library throttles the drag function on the carousel. This may not be desirable, or a custom throttle value might want to be preferred.

Add `throttle` to allow customization of drag throttle

---

src/utils/getSlidesVNodes.ts

Enhance getSlidesVNodes logic to recursively get nested child elements when the vNode type is Symobl(Fragment) 
fixes #291
fixes #277
fixes #72

enhance getSlidesVNodes logic

---

src/components/Slide.ts

Converted all of the isX values to computed refs. This means that the callbacks are only re-executed when dependent values change rather than every time the render function runs.
Also added all the isX values to the slotProps provided to slide. This can provide many useful functions to the end-user, including being able to respond to changes in visibility when using their own ARIA props inside the slot.

[Slide]: Performance improvements and slot props support

---

src/styles/navigation.css
src/styles/pagination.css

This PR wraps the hover classes under the [hover media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover) so that they are only applied when supported.
This would fix issue #320

[Pagination] Apply hover classes only on supported devices

---

src/components/Carousel.ts

Ensures the slides data gets updated when the window resizes to avoid the `minSlideIndex` and `maxSlideIndex` to be outdated when `itemsToShow` is overridden for a breakpoint.
Reproduceable example:
```
<Carousel
snap-align="center"
:items-to-show="1"
:breakpoints="{
1024: {
itemsToShow: 2,
snapAlign: 'start',
},
}"
>
</Carousel>
```
Note how the `maxSlideIndex` doesn't get adjusted from `2` to `1` when increasing the window size to above 1024px.
After this fix, the `maxSlideIndex` will be adjusted accordingly.

Update slides data on window resize

---

src/components/Carousel.ts

Resolves #362 by removing the `stopPropagation` in the _captured_ `dragend` event of the carousel.

allows successors to prevent default.

---

package.json

resolves external issue https://github.com/gaetansenn/vue3-carousel-nuxt/issues/12 and maybe #372.
Node's resolver loads "./dist/carousel.js" as "esm"!
I improved `package.json` with the help of https://github.com/vitejs/vite/discussions/2657#discussioncomment-5856909.

Full support for esm

---

src/components/Carousel.ts

This fixes #390 - elements further "down" DOM can't stop events reaching the Carousel because the Carousel uses Capture events, which start in the root of the DOM and work their way down to child elements. As such, they happen before anything inside the Carousel has a chance to handle them. This means it's impossible to prevent the Carousel from sliding from a child element (for example, an interactive component in a Slide).
Probably my lack of relevant skills, but I couldn't get the dependencies of this project to resolve in a clean VM, and after some hackery to get around that I got some Vue render-time errors related to refs which I didn't understand. As such, I haven't been able to properly test this change.

Stop using Capture phase events

---

src/partials/props.ts

- closes: https://github.com/ismail9k/vue3-carousel/issues/424

fix: invalid type for prop `height`

---

docs/config.md
docs/examples/ExampleDisable.vue
docs/test.md
src/components/Carousel.ts
src/components/Slide.ts
src/partials/defaults.ts
src/partials/props.ts
src/types/carousel.ts

- support enable disable carousel based on config (closes #381)

Feat support enable disable carousel

---

src/components/Carousel.ts
src/components/Navigation.ts
src/components/Pagination.ts
src/index.ts
src/types/carousel.ts

Better support for typescript and add CarouselExposed type

---

src/components/Carousel.ts
src/types/carousel.ts

- ensure hot reload works
- for better reactivity
Closes #383

fix(carousel): dynamically recalculate slots in render function

---

docs/.vitepress/config.js

I was trying to look something up in the docs and noticed that local search was not enabled in VitePress. It looks like this:

docs: enable local search

---

src/components/ARIA/ARIA.ts
src/components/Carousel/Carousel.ts
src/components/Carousel/carouselProps.ts
src/components/Icon/Icon.ts
src/components/Navigation/Navigation.ts
src/components/Pagination/Pagination.ts
src/components/Slide/Slide.ts
src/injectSymbols.ts

fix: exported symbol differs from internal

---

docs/addons.md
playground/App.vue
src/components/Pagination/Pagination.ts
src/components/Pagination/Pagination.types.ts
src/shared/constants.ts

Fixes #301 
Adds a prop `paginated` to the carousel pagination, that will change the pagination to be based on the number of pages (via itemsToShow) rather than the number of slides
So if you have 10 slides and 4 items to show, you have 3 pages and 3 clickable buttons instead of 10
The paginated prop has no effect if itemsToShow is 1

feat: add paginated navigation for carousel pagination

---

docs/api/data.md
docs/config.md
eslint.config.js
rollup.config.js
src/components/Carousel/Carousel.ts
src/components/Carousel/Carousel.types.ts
src/components/Carousel/carouselProps.ts
src/components/Navigation/Navigation.ts
src/components/Navigation/Navigation.types.ts
src/components/Pagination/Pagination.ts
src/components/Pagination/Pagination.types.ts
src/components/Slide/Slide.ts
src/components/Slide/Slide.types.ts
src/shared/types.ts
src/utils/createCloneSlides.ts
src/utils/getSnapAlignOffset.spec.ts
tests/components/RefCarousel.vue
tests/integration/navigation.spec.ts
tests/integration/pagination.spec.ts

This PR adds a carousel prop that can be given to the Pagination and Navigation components so they can externally control a carousel and are not required to be within the addon slot
A few warnings during build have been fixed
And #461 modified to only clamping to the number of slides if the `clamp` prop is provided as it is undesired behavior as a default
Documentation has been updated accordingly

Allow carousel ref to be passed to Pagination and Navigation

---

docs/config.md
playground/App.vue
src/components/Carousel/Carousel.ts
src/components/Carousel/carouselProps.ts
src/shared/constants.ts
src/shared/types.ts
src/utils/getDraggedSlidesCount.spec.ts
src/utils/getDraggedSlidesCount.ts

I've implemented the option for #480, as it was just what I was looking for.
Add a `threshold` option to allow users to customize when transitions are triggered.

feat: add threshold option for slide transition customization

---

playground/App.vue
src/components/Carousel/Carousel.css
src/components/Carousel/Carousel.ts
src/composables/useDrag.ts

fix: allow users to pinch zoom on mobile and prevent click properly only if user drags more than 10px
