docs/.vitepress/config.js
docs/.vitepress/theme/index.js
docs/examples.md
package-lock.json
package.json

Add demo in documentation closes #5

docs: add examples 

---

src/components/Carousel.ts
src/components/Slide.ts
src/partials/counter.ts

Fix shared counter between multiple carousels (closes #7)

fix: multiple carousels counter

---

src/components/Carousel.ts

Add tolerance to enhance dragging behavior (closes #4)

feat: add drag tolerance

---

package.json

chore: add declaration file entry

---

package-lock.json
package.json
src/components/Carousel.ts

fix: breakpoints issue

---

package-lock.json
package.json
src/components/Carousel.ts

fix: remove slide updating issue

---

docs/examples.md
docs/examples/ExampleAutoplay.vue
src/components/Carousel.ts

Hi @ismail9k 
Thanks for this package, it works really well! 
I was looking for something with autoplay capability and I saw it was in your todo. This adds basic support via config setting `autoplay` bound to the number of ms between slides. 
Thanks

Add support for autoplay

---

src/components/Carousel.ts

fix: drage event

---

package-lock.json
package.json
src/components/Carousel.ts

Watch props changes and update the carousel configs respectability (closes #67)

fix: updating configs

---

src/components/Carousel.ts

fix: slides are added directly without v-for

---

docs/examples/ExampleAutoplay.vue
docs/getting-started.md
package-lock.json
package.json
src/components/Carousel.ts

feat: ability to pause autoplay when the carousel has hovered

---

src/components/Navigation.ts
src/components/Pagination.ts

I am getting a form auto-submit error when clicking a button that doesn't define the type attribute.
The solution to this problem is to define type="button" for button tag.

Fix form submission issue when clicking on navigation and pagination.

---

src/components/Carousel.ts
src/types/carousel.ts

feat: enhance wrapping around

---

README.md
docs/examples/ExampleBasic.vue
docs/getting-started.md
src/components/Carousel.ts
src/components/Navigation.ts
src/partials/defaults.ts
src/partials/utils.ts
src/styles/navigation.css
src/types/carousel.ts

feat: support rtl direction

---

docs/api.md

Explain how to use these methods with an example.

Update API methods documentation

---

docs/examples/ExampleActiveClasses.vue
docs/examples/ExampleAutoplay.vue
docs/examples/ExampleBasic.vue
docs/examples/ExampleBreakpoints.vue
docs/examples/ExampleHiddenArrows.vue
docs/examples/ExamplePagination.vue
docs/examples/ExampleWrapAround.vue
src/components/Carousel.ts

Fix mouse dragging getting stuck 
closes #190
closes #206

Bug fix/#206/mouse drag stuck

---

docs/examples/ExampleBasic.vue
src/components/Carousel.ts
src/partials/props.ts

Enhance auto-play preformance
Stop autoplay if its value set to zero
closes #205

Bug fix/#205/auto play

---

src/components/Carousel.ts

fix: remove resize event listener

---

src/styles/slide.css

Fix sliding on iOS (closes #22)

[#22] Fix sliding on iOS devices

---

src/components/Carousel.ts

fix: reset autoplay

---

src/components/Carousel.ts

Correctly set modifiers for event handlers

---

docs/configs.md
docs/examples.md
docs/examples/ExampleBreakpoints.vue
docs/examples/ExamplePagination.vue
src/components/Carousel.ts

deprecation: remove settings prop in favor of v-bind
implements: #298

deprecation: remove settings prop in favor of v-bind

---

src/styles/pagination.css

Remove padding from carousel__pagination

---

docs/examples.md

[Docs] Update shown code to match demo component

---

docs/examples.md
package.json
src/components/ARIA.ts
src/components/Carousel.ts
src/components/Icon.ts
src/components/Navigation.ts
src/components/Pagination.ts
src/components/Slide.ts
src/partials/defaults.ts
src/partials/props.ts
yarn.lock

- [feat: update vitepress version](https://github.com/ismail9k/vue3-carousel/commit/fc84a68ef0e12bf7268361886a9118eeb4fe2a3b)
- [feat: improvments in generating default config](https://github.com/ismail9k/vue3-carousel/commit/bf803714997413aaf783d358200de01776d098a5)

Feat enhancments

---

src/utils/mapNumberToRange.spec.ts
src/utils/mapNumberToRange.ts

Fix infinite recursion in mapNumberToRange

---

src/utils/throttle.ts

- feat(utils): use requestAnimationFrame for throttle function
- implement #420

feat(utils): use requestAnimationFrame for throttle function

---

src/components/Carousel.ts

fix: cannot set properties on null (setting 'index') issue

---

src/components/Carousel.ts
src/utils/debounce.ts
src/utils/throttle.ts

- enhance: optimize resize event to reduce flickering while resizing
- refactor: update debounce function to use request animation frame
- refactor: update throttle function
- closes #340

340 carousel flickers when resizing it

---

docs/api/events.md

docs: update events file

---

package.json
rollup.config.js

Resolves https://github.com/ismail9k/vue3-carousel/issues/457

fix: reorder exports in `package.json`

---

src/components/Carousel/Carousel.css
src/components/Carousel/Carousel.ts
src/utils/getScrolledIndex.ts
tests/integration/__snapshots__/carousel.spec.ts.snap
tests/integration/carousel.spec.ts

- Fix cloned slides calculations
- Apply negative margin to handle cloned slides offset
- Add test coverage for cloned slides functionality
- Fix `getScrolledIndex` calculations for `wrapAround` configurations

445 configurable cloned items for wrap around

---

src/components/Carousel/Carousel.ts
src/composables/index.ts
src/composables/useDragging.ts
src/composables/useHover.ts

This PR aims to refactor dragging and hover functionality into composable components.
It introduces the useDrag and useHover composable functions to improve reusability and maintainability.

Refactor: Use Composable Functions
